on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags'
  push:
    branches:
      - main
    paths:
      - 'copyfolder/**'

jobs:
    replicate-file:
        runs-on: ubuntu-latest
        name: Replicate File
        
        steps:
        - name: Checkout Project A
          uses: actions/checkout@v2
          with:
            path: ./projectA

        - name: Checkout Project B
          uses: actions/checkout@master
          with: 
            repository: DevArchitectMaster/projectB
            token: ${{ secrets.ACTIONS_TOKEN }}
            path: ./projectB

        - name: Copy/Create file
          run: |
            FILE=./projectA/copyfolder/
            echo "Copying $FILE"
            cp -R $FILE ./projectB

        - name: Push Project B
          run: |
            cd ./projectB
            git add .
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -am "Files Replicated from Project A"
            git push